### PR TITLE
fix: replacing usecolormodevalue to _dark

### PR DESCRIPTION
**Pull request by gracebir**
## Describe your changes

replacing `useColorModeValue` with `_dark`

## Screenshots
Screenshot from 2023-09-04 12-08-28

### CODE REVIEW

**Comment by gracebir** [comment]
> ## Describe your changes
> closes #<issue_id>
> 
> ## Screenshots
> ## Documentation
> ## Checklist
> * [ ]  I performed a self review of my code
> * [ ]  I ensured that everything is written in English
> * [ ]  I tested the feature or fix on my local environment
> * [ ]  I ran the `yarn storybook` command and everything is working
> * [ ]  If applicable, I updated the translations for english and french files
>   (If you cannot update the french language, just let us know in the PR description)
> * [ ]  If applicable, I updated the README.md
> * [ ]  If applicable, I created a PR or an issue on the [documentation repository](https://github.com/bearstudio/start-ui-web-docs/)
> * [ ]  If applicable, I’m sure that my feature or my component is mobile first and available correctly on desktop

**Comment by ivan-dalmet** [comment]
Hi @gracebir!
Thanks a lot for this PR!
But unfortunately  it's seems broken :/ 
image

You can check here the issue in dark mode
https://start-ui-git-fork-gracebir-revert-usecolormodevalue-bearstudio.vercel.app/storybook/index.html?path=/docs/components-select--docs
image

**Comment by ivan-dalmet** [comment]
And by reading the code change, this will not work unfortunately.
The object that you updated needs to output real css not Chakra values ;)

**Comment by gracebir** [comment]
> And by reading the code change, this will not work unfortunately. The object that you updated needs to output real css not Chakra values ;)

@ivan-dalmet , could please you articulate, what do mean you by output real css?

**Comment by gracebir** [comment]
> > > And by reading the code change, this will not work unfortunately. The object that you updated needs to output real css not Chakra values ;)
> > 
> > 
> > @ivan-dalmet , could please you articulate, what do mean you by output real css?
> 
> The library we are using for the `Select` component is [`react-select`](https://react-select.com) and to customize the `react-select` [styles](https://react-select.com/styles), we can't use Chakra UI "selectors" like `_hover` or `_dark`. I think we need to provide real [CSS in JS](https://cssinjs.org/?v=v10.10.0) for this component.
> 
> Also, we can't use Chakra variables as is (like `brand.600`) because it has no value in CSS, we need to convert it before (using Chakra's helper) so `brand.600` become a CSS value like `#ad032c` for example.

sure @yoannfleurydev

**Pull request closed without merging**
