### PR TITLE
feat: add query-key-factory library + integration

### PR DESCRIPTION
**Pull request by HugoPerard**
I integrate query-key-factory library to replace our custom query keys on services files.
I think it's more simple to write, to understand and to use.

### CODE REVIEW

**Comment by Rileran** [comment]
Great lib to reduce boilerplate !

**Comment by HugoPerard** [comment]
I put this on draft because of query-key-factory library evolutions, I need to update this PR

**Comment by HugoPerard** [comment]
The lib looks to be more stable, I update my PR with the 0.6.1 version

**Review by DecampsRenan — APPROVED** [review]
Approved, but not really a big fan of `_def` / `.queryKey` accessors ^^

**Pull request merged**
