### PR TITLE
Fixed: README  ERROR

### PR DESCRIPTION
**Pull request by winner106**
fix: README

### CODE REVIEW

**Comment by ivan-dalmet** [comment]
Hi @winner106,
I'm not sure to understand this change, this is an example.

**Comment by winner106** [comment]
> Hi @winner106,
> 
> I'm not sure to understand this change, this is an example.

yes, in the example, json key was not match your context name

**Comment by yoannfleurydev** [comment]
> > Hi @winner106,
> > I'm not sure to understand this change, this is an example.
> 
> yes, in the example, json key was not match your context name

To be correct, I think this should be `resetSuccess` and `resetError` to match the context name because those are related to the password reset and not the password update. Also, can you please update them in the code if possible ? You can say no, I'll create an issue if needed 😊

**Comment by winner106** [comment]
ok，I will be pleasure to make my first pr, thanks!

**Review by HugoPerard — APPROVED** [review]

**Comment by carlbrewer20211** [comment]
Google





KASY OMO_Jeje


KASY OMO_Jeje

DOLLAR 💵 💰 VIBES


Tulsa Live Stream


Tulsa Live Stream

8726 E 41st St, Tulsa, OK 74145, United States

+1 539-777-0114






View on Google Maps




Google

© 2018 Google LLC 1600 Amphitheatre Parkway, Mountain View, CA 94043

Sent by KASY OMO_Jeje via Google Maps

**Pull request merged**
