### PR TITLE
Fix - Align Toast icon with the title

### LINKED ISSUE #392: Toast Icon is not aligned with the Title
# Description

As seen on this screen taken on the StartUI demo, the icon and the title are not aligned.
image

## How to fix 

The fix is quite simple. In the `alert.ts` file, change the icon height from 4 to 6 to match the title lineHeight)

## Result after fix

image

### PR DESCRIPTION
**Pull request by ntatoud**
## Describe your changes

Changed the alert custom style to align the icon with the title of the toast

closes #392

In the file `src/theme/components/alert.ts`, inside `alertTheme` : 

- Changed the `icon.h` to match `title.lineHeight`. In this case `6`
The difference beteween `icon.h` and `icon.w` is not a problem since the icon is an svg, it won't be transformed.

**EDIT** : 
- The `spinner` however is less convenient since its shape changes if  `spinner.h != spinner.w`.
After looking at Chakra Toast initial value, I replaced the value to `spinner.h=5` and `spinner.w=5` and it works just fine.
In any case, the loading toast is not used in StartUI at the moment.

** FINAL EDIT**:
To simplify the code, we should just remove these parameters and make the Alert Icon more like the default one from ChakraUI
## Screenshots
**Before Fix:**
image

**After Fix:**
image

## Checklist

 - [x] I performed a self review of my code
 - [x] I ensured that everything is written in English
 - [x] I tested the feature or fix on my local environment
 - [x] I ran the `yarn storybook` command and everything is working

### CODE REVIEW

**Comment by ivan-dalmet** [comment]
This fix break the loading state on alerts 😕[Screenshot_20230711_063744.jpg](https://github.com/BearStudio/start-ui-web/assets/9749061/1f4cd93d-1b42-4194-b196-80a1305441b5)

**Review by ivan-dalmet — CHANGES_REQUESTED** [review]
This fix break the loading state on alerts 😕[Screenshot_20230711_063744.jpg](https://github.com/BearStudio/start-ui-web/assets/9749061/1f4cd93d-1b42-4194-b196-80a1305441b5)

I think that we need another way to fix because height and width of the icon should always be the same.

**Comment by ntatoud** [comment]
Could you elaborate on this behavior ? Because I performed some tests locally and I obtained this results : 
For Toasts and Alerts
toastAlert

In the storybook :
loadingAlert

- It is true that at first the spinner was broken but I amended my commit to change the spinner width and height to 5

- As for the height and width being different, it is how it is done by default in Chakra. I just adapted it to startUI since the icon is smaller than the default one.

**Comment by ivan-dalmet** [comment]
@ntatoud look at the deployed storybook here for this PR 
https://start-ui-git-fork-ntatoud-fix-toast-icon-not-aligned-bearstudio.vercel.app/storybook/index.html?path=/story/styleguide-alerts--loading

**Comment by ntatoud** [comment]
@ivan-dalmet 
I think I understand the problem.

- I pushed my modification
- The app deployed
- I amended the last commit and it appears right in the `Changed Files` 
BUT : The app was not re-deployed, thus the previous, wrong version is displayed on the storybook.
- You requested changes
- Now the app will not redeploy without authorization :sweat_smile:

**Comment by ntatoud** [comment]
@ivan-dalmet I forgot to ping you but I think this can be merged

**Review by ivan-dalmet — APPROVED** [review]

**Pull request merged**
